name: test key

on:
  push:

jobs:

  testing:
    name: testing
    runs-on: ubuntu-latest

    steps:

    - name: Use secret key
      env:
        SECRET_KEY: ${{ secrets.DEPLOY_KEY }}
      run: |
        eval "$(ssh-agent -s)"
        umask 077
        echo "$SECRET_KEY" > ${{ runner.temp }}/key
        ssh-add ${{ runner.temp }}/key
        ssh-add -l

