name: test key

on:
  push:

jobs:

  testing:
    name: testing
    runs-on: ubuntu-latest

    steps:

    - name: Use secret key
      env:
        SECRET_KEY: "${{ secrets.DEPLOY_KEY }}"
      run: |
        eval "$(ssh-agent -s)"
        ssh-add <<< "$SECRET_KEY"
        ssh-add -l

