name: test key

on:
  push:

jobs:

  testing:
    name: testing
    runs-on: ubuntu-latest

    steps:

    - name: Use secret key
      env:
        SECRET_KEY: "${{ secrets.DEPLOY_KEY }}"
      run: |
        echo 0
        eval "$(ssh-agent -s)"
        echo 1
        ssh-add <<< "$SECRET_KEY"
        echo 2
        ssh-add -l
        echo 3

