name: test key

on:
  push:

jobs:

  testing:
    name: testing
    runs-on: ubuntu-latest

    steps:

    - name: Use secret key
      env:
        # SECRET_KEY: "${{ secrets.DEPLOY_KEY }}"
        M_SECRET: ${{ secrets.MULTI_LINE }}
      run: |
        # eval "$(ssh-agent -s)"
        # umask 077
        # 'ssh-add <<< "$SECRET_KEY"'
        # ssh-add -l
        rev <<< "$M_SECRET"

